<a href="https://colab.research.google.com/github/nanyolivei/dio-lab-open-source/blob/main/Projeto_DIO_ETL_Python_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Projeto DIO - ETL Python**

**Problema:** um jovem casal irá realizar a primeira viagem internacional para o Estados Unidos e precisam realizar uma organização financeira. Desta forma, eles decidem avaliar o câmbio do dolar nos últimos dois anos.

# **Extract**

Extração dos dados abertos do Banco do Brasil.

In [10]:
import pandas as pd

In [18]:
# Passo 1: Extração de Dados
# Suponha que você tenha um arquivo CSV chamado "dados.csv"
dados_df = pd.read_csv("dados_dolar_bcbrasil.csv")

print(dados_df)

                 data;"valor"
28/11/1984;"2828        0000"
29/11/1984;"2828        0000"
30/11/1984;"2881        0000"
03/12/1984;"2881        0000"
04/12/1984;"2881        0000"
...                       ...
08/09/2023;"4           9835"
11/09/2023;"4           9366"
12/09/2023;"4           9505"
13/09/2023;"4           9171"
14/09/2023;"4           8751"

[9721 rows x 1 columns]

In [16]:
import pandas as pd

In [22]:
import pandas as pd

# Ler o arquivo CSV usando ponto e vírgula como separador
df = pd.read_csv("dados_dolar_bcbrasil.csv", sep=";", header=None, names=["Data", "Valor"])

In [26]:
df["Valor"] = df["Valor"].str.strip()

print(df)

            Data      Valor
0           data      valor
1     28/11/1984  2828,0000
2     29/11/1984  2828,0000
3     30/11/1984  2881,0000
4     03/12/1984  2881,0000
...          ...        ...
9717  08/09/2023     4,9835
9718  11/09/2023     4,9366
9719  12/09/2023     4,9505
9720  13/09/2023     4,9171
9721  14/09/2023     4,8751

[9722 rows x 2 columns]

# Passo 2: Transformação de Dados

Calcular as médias, medianas, máximos e mínimos por ano para ter uma estimativa do dólar no ano da viagem.

In [33]:
import pandas as pd

import statistics

In [42]:
df = pd.read_csv('dados_dolar_bcbrasil.csv', delimiter=';', decimal=',')

In [43]:
df.head(10)

         data   valor
0  28/11/1984  2828.0
1  29/11/1984  2828.0
2  30/11/1984  2881.0
3  03/12/1984  2881.0
4  04/12/1984  2881.0
5  05/12/1984  2923.0
6  06/12/1984  2923.0
7  07/12/1984  2923.0
8  10/12/1984  2965.0
9  11/12/1984  2965.0

In [44]:
df.columns

Index(['data', 'valor'], dtype='object')

In [45]:
df.shape

(9721, 2)

In [47]:
df.dtypes

data      object
valor    float64
dtype: object

In [48]:
df['data']

0       28/11/1984
1       29/11/1984
2       30/11/1984
3       03/12/1984
4       04/12/1984
           ...
9716    08/09/2023
9717    11/09/2023
9718    12/09/2023
9719    13/09/2023
9720    14/09/2023
Name: data, Length: 9721, dtype: object

In [61]:
date_col = pd.DatetimeIndex(df['data'])

df['Ano'] = date_col.year
df['Mes'] = date_col.month
df['Dia'] = date_col.day

print(df)

            data      valor   Ano  Dia  Mes
0     28/11/1984  2828.0000  1984   28   11
1     29/11/1984  2828.0000  1984   29   11
2     30/11/1984  2881.0000  1984   30   11
3     03/12/1984  2881.0000  1984   12    3
4     04/12/1984  2881.0000  1984   12    4
...          ...        ...   ...  ...  ...
9716  08/09/2023     4.9835  2023    9    8
9717  11/09/2023     4.9366  2023    9   11
9718  12/09/2023     4.9505  2023    9   12
9719  13/09/2023     4.9171  2023   13    9
9720  14/09/2023     4.8751  2023   14    9

[9721 rows x 5 columns]

<ipython-input-61-ac8f9f750dd5>:1: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  date_col = pd.DatetimeIndex(df['data'])

In [63]:
#Visualizar a coluna

df.Ano

0       1984
1       1984
2       1984
3       1984
4       1984
        ...
9716    2023
9717    2023
9718    2023
9719    2023
9720    2023
Name: Ano, Length: 9721, dtype: int64

In [69]:
#Selecionar múltiplas colunas

df.loc[:,['Ano','Dia','valor']]

       Ano  Dia      valor
0     1984   28  2828.0000
1     1984   29  2828.0000
2     1984   30  2881.0000
3     1984   12  2881.0000
4     1984   12  2881.0000
...    ...  ...        ...
9716  2023    9     4.9835
9717  2023    9     4.9366
9718  2023    9     4.9505
9719  2023   13     4.9171
9720  2023   14     4.8751

[9721 rows x 3 columns]

In [71]:
#Trasnformando a tabela com apenas dados do ano de 2022

df[df['Ano'].isin([2022])]

            data   valor   Ano  Dia  Mes
9293  03/01/2022  5.6309  2022    1    3
9294  04/01/2022  5.6776  2022    1    4
9295  05/01/2022  5.6628  2022    1    5
9296  06/01/2022  5.7042  2022    1    6
9297  07/01/2022  5.6753  2022    1    7
...          ...     ...   ...  ...  ...
9539  26/12/2022  5.1872  2022   26   12
9540  27/12/2022  5.2832  2022   27   12
9541  28/12/2022  5.2736  2022   28   12
9542  29/12/2022  5.2177  2022   29   12
9543  30/12/2022  5.2177  2022   30   12

[251 rows x 5 columns]

In [89]:
ano_desejado = dados_do_ano
dados_do_ano = df[df['Ano'].isin([2022])]

print(ano_desejado)

            data   valor   Ano  Dia  Mes
9293  03/01/2022  5.6309  2022    1    3
9294  04/01/2022  5.6776  2022    1    4
9295  05/01/2022  5.6628  2022    1    5
9296  06/01/2022  5.7042  2022    1    6
9297  07/01/2022  5.6753  2022    1    7
...          ...     ...   ...  ...  ...
9539  26/12/2022  5.1872  2022   26   12
9540  27/12/2022  5.2832  2022   27   12
9541  28/12/2022  5.2736  2022   28   12
9542  29/12/2022  5.2177  2022   29   12
9543  30/12/2022  5.2177  2022   30   12

[251 rows x 5 columns]

**Load**

Criar um novo arquivo com as novas colunas criadas e realizar a análise de dados em uma outra ferramenta.

In [90]:
novo_arquivo_csv = 'dados_transformados.csv'

df.to_csv(novo_arquivo_csv, index=False)